### ISSUE TITLE
false reporting asset duplication

### ISSUE THREAD

**Issue by sophiepeithos** [Unity-Technologies/AssetBundles-Browser#51] opened 2017-11-17 09:33 UTC
material a use texture b, cube c use material a, give material a and cube c each a unique bundle name, then save project, then assetbundle browser will report texture b will cause duplication in memory.

**Comment by alffanclub** [comment] 2017-11-21 22:10
Thanks for submitting this @sophiepeithos.  This makes sense and I shouldn't have any trouble reproducing it.  I'm not 100% sure I can fix it without going to a hierarchical view of dependencies.  If that's the case, then I may need to shelve this bug while working on that view (it is in the works). Will update here if I have any useful info. 
Thanks again for submitting this,
Bill

**Comment by D3m0n92** [comment] 2018-01-23 14:40
Same issue. It is probably due to the fact that I created an asset bundle, then I deleted it, reimported the model and tried to rebuild a bundle (without building).

**Comment by alffanclub** [comment] 2018-10-01 19:41
I'm going to close this one out, though I don't really like that.  It's a real issue, but the way I can get dependencies forces me into this corner.  It is possible to do a more hierarchical query, but it introduces some other issues, as well as taking MUCH MUCH longer to compute.  Switching to the hierarchical model would be essentially unusable for large projects.

**Closed by alffanclub** 2018-10-01 19:41 UTC
