### ISSUE TITLE
Multiscene lightmapping creates a recursive dependency on the AssetBundle system

### ISSUE THREAD

**Issue by jbonastre** [Unity-Technologies/AssetBundles-Browser#50] opened 2017-11-16 11:31 UTC
Multiscene lightmapping creates a recursive dependency on the AssetBundle system.

1. What happened
Multiscene lightmapping creates a recursive dependency on the AssetBundle system.

2. How we can reproduce it using the example you attached
Open the scene SceneLighting, add the scene Scene1, add the scene Scene2.
Open the lighting tab and press "Generate Lighting" button
Save scenes and project
Open the Asset Bundles browser and check the bundles dependencies. There is a recursive dependency between all the bundles!!!

Have a look to the bug 965309, there is a repro project.

**Comment by alffanclub** [comment] 2017-11-20 17:02
@jbonastre  Just so I understand fully, do the bundles build correctly?  I can't tell from reading your description if the recursive loop is a bundle-browser-only issue, or if the final resulting bundles are somehow built wrong (or not built at all).
Thanks for submitting this.

**Comment by jbonastre** [comment] 2017-11-20 21:54
The asset bundles are built correctly, however there appears a recursive dependency. I don't know if it should be assigned to the Lighting team (I´ve contacted with William Armstrong on Twitter for the same issue).

**Comment by alffanclub** [comment] 2017-11-20 21:56
If things are building correctly, than the issue is most likely with the Browser and not the lighting team. I'll look into it and can contact the lighting team if need be.
Thanks again.

**Comment by alffanclub** [comment] 2017-12-05 14:59
ok, @jbonastre I have looked into this, and discussed it with the lighting team.  Here's the summary:
- when you bake lights for multiple scenes together it creates one asset with multiple objects (one per scene) in that asset. The actual bundle building pulls in dependencies at the object level, but the browser operates at the asset level. So the browser thinks that all three of your bundles will need this single lighting asset. In reality, the asset is broken down and each bundle only needs the portion it pulls in. There isn't really a way to fix this in the browser because object level dependencies aren't currently exposed. 
- So, what to do about your specific situation? Well, from talking to the lighting team, I believe the workflow of lighting scenes together, but bundling them separately isn't quite ideal.  When you light them together, items in each scene cast shadows/etc. on/with items in the other scenes. So if your use-case is that in-game you have all these scenes open at once, then they should be lit together, and in one bundle together. If your use-case is that the scenes will not be loaded together, then they should be lit independently, and bundled independently.
 I hope that makes sense. Sorry I'm unable to get this fixed with the browser.  We will keep this scenario in mind as we work on the future bundling systems coming sometime in 2018.

**Comment by jbonastre** [comment] 2017-12-06 09:30
Hi,

In our case, we are baking a base scene, the lighting scene and a variant
scene by country. So, we bake all the scenes together, but only a set of
these is deployed to the customer (according to his country).

Anyway, we found a workaround: we avoid to load a bundle dependency if it´s
a scene bundle.

2017-12-05 15:59 GMT+01:00 Bill <notifications@github.com>:

**Closed** 2017-12-06 14:56 UTC
