### ISSUE TITLE
Unable to detect Asset Graph 

### ISSUE THREAD

**Issue by PuzzledBoy** [Unity-Technologies/AssetBundles-Browser#62] opened 2018-01-04 10:03 UTC
Test in Unity5.6.4p2 and Unity2017.2.0f3.

**Comment by alffanclub** [comment] 2018-01-04 16:53
Hi @PuzzledBoy thanks for reaching out. Could you give me some additional details? What exactly do you mean by Asset Graph? Is it the Asset Graph Tool located here: https://bitbucket.org/Unity-Technologies/assetbundlegraphtool? If so, do you mean that you can't pick it as a data source, or is there some other issue?
If you aren't talking about the graph tool, then I'd ask what Asset Graph are you referring to, and how is it not detected?
Thanks again for posting, we want to make sure all issues are dealt with when possible.

**Comment by 0jb** [comment] 2018-02-10 14:02
I'm having a similar issue, where my configured graphs are not shown on asset bundle browser.

The asset bundle graph doesn't even show up on the on the Bundle Data Source dropdown on the browser window.

Some workarounds that I have tried:

* Creating multiple graphs;
* Cleaning up all assignments and making the bundles from scratch on the Graph tool;
* Disabling Unity's cache, deleting Library folder and reimporting the project;
* Closing and opening Unity;
* Clicking refresh button on the Browser multiple times;
* Clicking "Reload all Data";

If you need more details please let me know.

**Comment by 0jb** [comment] 2018-02-10 14:16
So! I think I found a solution. My original install order was the following:

I installed first the browser tool and then graph tool. It seems like the browser won't detect the graph if graph is imported after browser is already imported. It doesn't really makes sense to me, but it works.

It also could be that I manually downloaded the repository and added it to my project on a custom plugin folder. The second time I downloaded from Asset Store, so it was installed directly on my project root. Don't know why this worked but hope this is helpful :)

**Comment by PuzzledBoy** [comment] 2018-02-10 14:40
I'm sorry for my late, somethings happens on me the last months I even forget my post.
Yes, @alffanclub the AssetGraph means the Graph Tool you mentions.
I see the video https://www.youtube.com/watch?v=r1kslvqXAq8 can select a Bundle Data Source from the Graph Tool. But It don't work in my case. 
![4](https://user-images.githubusercontent.com/7671107/36063080-57960052-0eb3-11e8-8e75-359a8de9112c.png)

**Comment by PuzzledBoy** [comment] 2018-02-10 14:51
Hi , @0jb.
Thanks you , I import the Browser from AssetStore instead of github,then it work.
Don't know why yet. :)

**Comment by BernsteinA** [comment] 2018-08-17 14:17
add `ASSETBUNDLE_BROWSER_GRAPH_INTEGRARION` (sic) to your build settings' Scripting Define Symbols.
https://bitbucket.org/Unity-Technologies/assetbundlegraphtool/src/bd75fe083164567710471e7fee2c5a93d6d2722c/UnityEngine.AssetGraph/Integration/Editor/AssetBundles-Browser/GraphToolABDataSource.cs?at=1.4%2Frelease&fileviewer=file-view-default#GraphToolABDataSource.cs-10

**Comment by alffanclub** [comment] 2018-10-01 18:35
The issue is that all packages must be in their own assemblies (having an `asmdef` file in some specific places). The original way we integrated this tool and the graph tool was to use a partial class that spanned the two code bases.  That can no longer be done with the browser being in a unique assembly. If you pull the browser from github instead of packaman, and remove the asmdef's you can make it work.  Alternatively, it looks like (based on the link above) that the graph tool has some work being done to function with the browser despite the assembly issue.  I am not sure what the exact status of this work is on the graph too.

**Closed by alffanclub** 2018-10-01 18:35 UTC
