### ISSUE TITLE
Missing Asset Graph selection at AssetBundles Browser

### ISSUE THREAD

**Issue by optimisez** [Unity-Technologies/AssetBundles-Browser#72] opened 2018-01-30 13:55 UTC
The Asset Graph selection that should exist at AssetBundles Browser is missing in Unity 2017.3

The following is the commit I used: 
Asset Graph 1.4 (74d41ff): https://bitbucket.org/Unity-Technologies/assetbundlegraphtool/commits/74d41ff90c5def58b9bbc5b643f2c7fe1057bdd5 

AssetBundles-Browser (aede802) : https://github.com/Unity-Technologies/AssetBundles-Browser/commit/aede8021c0e01a931dda3d0ba7495a016c191a25

![image](https://user-images.githubusercontent.com/7009368/35569783-0fcde98c-0608-11e8-9e9a-84ee73b4114e.png)

**Comment by 0jb** [comment] 2018-02-10 20:42
https://github.com/Unity-Technologies/AssetBundles-Browser/issues/62

**Comment by BernsteinA** [comment] 2018-08-17 14:06
add `ASSETBUNDLE_BROWSER_GRAPH_INTEGRARION` (sic) to your build settings' Scripting Define Symbols.
https://bitbucket.org/Unity-Technologies/assetbundlegraphtool/src/bd75fe083164567710471e7fee2c5a93d6d2722c/UnityEngine.AssetGraph/Integration/Editor/AssetBundles-Browser/GraphToolABDataSource.cs?at=1.4%2Frelease&fileviewer=file-view-default#GraphToolABDataSource.cs-10

**Comment by alffanclub** [comment] 2018-10-01 18:35
as mentioned above, this is a duplicate of #62

**Closed by alffanclub** 2018-10-01 18:35 UTC
