### ISSUE TITLE
Creating corrupted AssetBundles if using FBX with embedded materials.

### ISSUE THREAD

**Issue by Sacristan** [Unity-Technologies/AssetBundles-Browser#68] opened 2018-01-17 11:22 UTC
![screenshot_2018-01-16-19-20-07](https://user-images.githubusercontent.com/3949694/35040200-edbb5098-fb88-11e7-8345-ea0d5a371ca0.png)

![23fc5920bf817a4bc26b822f71ae7e47](https://user-images.githubusercontent.com/3949694/35040275-1ee52824-fb89-11e7-8f78-44e2102cba59.png)

Corrupted AssetBundle Mesh data is being created  if FBX Importer has imported materials as embedded.

https://docs.unity3d.com/Manual/FBXImporter-Materials.html
Unity has introduced this feature 2017.2

**Comment by alffanclub** [comment] 2018-01-18 21:17
Hi @Sacristan, I believe this is the same root cause as: https://issuetracker.unity3d.com/issues/editor-crashes-when-loading-a-mesh-asset-with-mesh-compression-from-an-assetbundle.

The issue is being worked on by the engine team. It seems to be caused when some meshes are compressed and some are not. From what I've gathered it definitely is fine if you turn off mesh compression for all meshes, but I believe it's also fine if you turn it on for *all* meshes. In either case, you can still compress the bundle however you please. If you subscribe to the above linked bug, you should be able to get info once it's resolved.

Thanks for reaching out,
Bill

**Comment by alffanclub** [comment] 2018-10-01 18:38
The engine issue was resolved in 2018.2

**Closed by alffanclub** 2018-10-01 18:38 UTC
